#!/bin/bash

# Script para ver la estructura del proyecto creado

echo "═══════════════════════════════════════════════════════════════"
echo "📦 ESTRUCTURA DEL PROYECTO CREADO"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📁 Raíz del Proyecto:"
echo "   - docker-compose.yml         (Configuración principal)"
echo "   - README.md                  (Documentación)"
echo "   - INICIO_RAPIDO.md           (Guía de 5 minutos) ⭐"
echo "   - ARQUITECTURA.md            (Diseño del sistema)"
echo "   - ESTRUCTURA_PROYECTO.md     (Árbol de directorios)"
echo "   - INTEGRACION_BACKEND.md     (Guía Spring Boot)"
echo "   - EJEMPLOS_EVENTOS.md        (Eventos Kafka)"
echo "   - TESTING.md                 (Pruebas)"
echo "   - COMPLETADO.md              (Resumen)"
echo "   - start.sh / stop.sh         (Scripts)"
echo ""

echo "📁 notifications-service/ (FastAPI - Puerto 8002)"
echo "   ├── app/"
echo "   │   ├── main.py              (Aplicación FastAPI)"
echo "   │   ├── config.py            (Configuración)"
echo "   │   ├── models/              (Modelos BD)"
echo "   │   ├── schemas/             (Validación Pydantic)"
echo "   │   ├── routes/              (Endpoints REST)"
echo "   │   ├── services/            (Lógica negocio)"
echo "   │   └── kafka/               (Consumidor Kafka)"
echo "   ├── requirements.txt         (Dependencias)"
echo "   ├── Dockerfile               (Imagen Docker)"
echo "   └── .env.example             (Variables)"
echo ""

echo "📁 email-service/ (FastAPI - Puerto 8003)"
echo "   ├── app/"
echo "   │   ├── main.py              (Aplicación FastAPI)"
echo "   │   ├── config.py            (Configuración)"
echo "   │   ├── models/              (Modelos BD)"
echo "   │   ├── schemas/             (Validación Pydantic)"
echo "   │   ├── routes/              (Endpoints REST)"
echo "   │   ├── services/            (Lógica negocio)"
echo "   │   ├── kafka/               (Consumidor Kafka)"
echo "   │   └── templates/           (Plantillas HTML)"
echo "   ├── requirements.txt         (Dependencias)"
echo "   ├── Dockerfile               (Imagen Docker)"
echo "   └── .env.example             (Variables)"
echo ""

echo "📁 docker/ (Configuración)"
echo "   ├── mysql-init.sql           (Inicialización BD)"
echo "   ├── haproxy.cfg              (API Gateway)"
echo "   └── create-topics.sh          (Kafka topics)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 COMANDOS RÁPIDOS"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "Inicio rápido:"
echo "  docker-compose up -d                    # Iniciar servicios"
echo "  docker-compose ps                       # Ver estado"
echo "  docker-compose logs -f                  # Ver logs en vivo"
echo ""

echo "Testing:"
echo "  curl http://localhost:8002/health       # Test Notif."
echo "  curl http://localhost:8003/health       # Test Email"
echo "  http://localhost:8002/docs              # Swagger Notif."
echo "  http://localhost:8003/docs              # Swagger Email"
echo ""

echo "Detener:"
echo "  docker-compose down                     # Detener"
echo "  docker-compose down -v                  # Detener + limpiar"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTACIÓN"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "Comienza por:"
echo "  1️⃣  INICIO_RAPIDO.md          (Lee primero - 5 min)"
echo "  2️⃣  README.md                 (Visión general)"
echo "  3️⃣  ARQUITECTURA.md           (Diseño del sistema)"
echo "  4️⃣  INTEGRACION_BACKEND.md    (Integración Spring Boot)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✨ SERVICIOS DISPONIBLES"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🔔 Notificaciones Service"
echo "   URL: http://localhost:8002"
echo "   Swagger: http://localhost:8002/docs"
echo ""

echo "📧 Email Service"
echo "   URL: http://localhost:8003"
echo "   Swagger: http://localhost:8003/docs"
echo ""

echo "🌐 API Gateway (HAProxy)"
echo "   URL: http://localhost:8080"
echo "   Stats: http://localhost:8080/stats"
echo ""

echo "🗄️  MySQL Database"
echo "   Host: localhost:3306"
echo "   User: user"
echo "   Pass: password"
echo "   DB: proyectos_db"
echo ""

echo "🍃 Kafka Broker"
echo "   Address: localhost:9092"
echo ""

echo "📦 Redis Cache"
echo "   Address: localhost:6379"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ COMPLETADO Y LISTO PARA USAR"
echo "═══════════════════════════════════════════════════════════════"
echo ""
